In [1]:
#Importing libraries to test
import numpy as np
from neural_network import relu, softmax, one_hot

In [8]:
#Testing one_hot function
y_test = np.array([0,1,2,0])
y_hot = one_hot(y_test, 3)
print(f"y_hot array: \n {y_hot}")
print(f"y_hot shape: {y_hot.shape}")
print(f"column 0 of y_hot: {y_hot[:,0]}")

y_hot array: 
 [[1. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
y_hot shape: (3, 4)
column 1 of y_hot: [1. 0. 0.]


In [12]:
#Testing softmax function
Z_test = np.array([[10, 0, 100],
                   [10, 0, 100]])
A_test = softmax(Z_test)
print(f"Softmax Columns{np.sum(A_test, axis = 0)}")
print(f"Softmax col 0: {A_test[:,0]}")

Softmax Columns[1. 1. 1.]
Softmax col 0: [0.5 0.5]


In [15]:
#Testing relu function
Z_relu = np.array([[-1, 2],
                   [0, -5]])
rel = relu(Z_relu)
print(f"Relu result: \n {rel}")

Relu result: 
 [[0 2]
 [0 0]]
